### ISSUE TITLE
WARNING: Published service message input is not licensed

### ISSUE THREAD

**Issue by martinborgman** [CAAPIM/Microgateway#21]
microgateway_ssg_1 remains unhealthy.
log show many warnings and errors such as WARNING: Published service message input is not licensed.

**Comment by sbourlon** [comment]
Hi @martinborgman,

I renewed yesterday the trial license which expired on February 2nd. Could you try the latest version of the master branch? Thanks.

**Comment by martinborgman** [comment]
Hi @sbourlon 

This license works, thank you.

**Comment by sbourlon** [comment]
@martinborgman, Awesome!

Feel free to give feedback and ask additional questions! Thanks.
